# **Bioinformatics Project - Computational Drug Discovery [Part 3] Descriptor Calculation and Dataset Preparation**

Chanin Nantasenamat

[*'Data Professor' YouTube channel*](http://youtube.com/dataprofessor)

In this Jupyter notebook, we will be building a real-life **data science project** that you can include in your **data science portfolio**. Particularly, we will be building a machine learning model using the ChEMBL bioactivity data.

In **Part 3**, we will be calculating molecular descriptors that are essentially quantitative description of the compounds in the dataset. Finally, we will be preparing this into a dataset for subsequent model building in Part 4.

---

## **Download PaDEL-Descriptor**

In [41]:
! wget https://github.com/dataprofessor/bioinformatics/raw/master/padel.zip
! wget https://github.com/dataprofessor/bioinformatics/raw/master/padel.sh

wget: /usr/local/lib/libuuid.so.1: no version information available (required by wget)
--2022-02-01 10:49:35--  https://github.com/dataprofessor/bioinformatics/raw/master/padel.zip
Resolving github.com (github.com)... 20.201.28.151
Connecting to github.com (github.com)|20.201.28.151|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/dataprofessor/bioinformatics/master/padel.zip [following]
--2022-02-01 10:49:36--  https://raw.githubusercontent.com/dataprofessor/bioinformatics/master/padel.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 25768637 (25M) [application/zip]
Saving to: ‘padel.zip.1’

padel.zip.1         100%[===================>]  24,57M  42,5MB/s    in 0,6s

2022-02-01 10:49:37 (42,5 MB/s) - ‘padel.zip.1’ saved [25768637/25768637]

wget: /usr/local/lib/libuuid.so.1: no version information available (required by wget)
--2022-02-01 10:49:38--  https://github.com/dataprofessor/bioinformatics/raw/master/padel.sh
Resolving github.com (github.com)... 20.201.28.151
Connecting to github.com (github.com)|20.201.28.151|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/dataprofessor/bioinformatics/master/padel.sh [following]
--2022-02-01 10:49:38--  https://raw.githubusercontent.com/dataprofessor/bioinformatics/master/padel.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 231 [text/plain]
Saving to: ‘padel.sh.1’

padel.sh.1          100%[===================>]     231  --.-KB/s    in 0s

2022-02-01 10:49:38 (5,29 MB/s) - ‘padel.sh.1’ saved [231/231]

In [42]:
! unzip padel.zip

Archive:  padel.zip
  inflating: __MACOSX/._PaDEL-Descriptor
replace PaDEL-Descriptor/MACCSFingerprinter.xml? [y]es, [n]o, [A]ll, [N]one, [r]ename: ^C

## **Load bioactivity data**

Download the curated ChEMBL bioactivity data that has been pre-processed from Parts 1 and 2 of this Bioinformatics Project series. Here we will be using the **bioactivity_data_3class_pIC50.csv** file that essentially contain the pIC50 values that we will be using for building a regression model.

In [1]:
import pandas as pd

In [2]:
! pwd

/home/jaime/Dropbox/Tesis/jupiter_notebook/07_clases_10000_5000_dock_3+/notebook

In [3]:
! ls -la

total 99892
drwxr-xr-x 5 jaime jaime     4096 feb  1 16:05 .
drwxr-xr-x 5 jaime jaime     4096 feb  1 16:01 ..
-rw-r--r-- 1 jaime jaime  3916980 feb  1 16:01 bioactivity_data.csv
-rw-rw-r-- 1 jaime jaime   212391 feb  1 16:03 bioactivity_preprocessed_data.csv
-rw-rw-r-- 1 jaime jaime  4588992 feb  1 16:01 descriptors_output.csv
-rw-rw-r-- 1 jaime jaime     1257 feb  1 16:05 histograma.png
-rw-rw-r-- 1 jaime jaime    57463 feb  1 16:01 ids_3+.csv
-rw-rw-r-- 1 jaime jaime    27816 feb  1 16:01 ids_todos.csv
drwxr-xr-x 2 jaime jaime     4096 feb  1 16:01 .ipynb_checkpoints
drwxr-xr-x 6 jaime jaime     4096 feb  1 16:01 jupyterenv
-rw-rw-r-- 1 jaime jaime      122 feb  1 16:05 mannwhitneyu_LogP.csv
-rw-rw-r-- 1 jaime jaime      122 feb  1 16:05 mannwhitneyu_MW.csv
-rw-rw-r-- 1 jaime jaime      132 feb  1 16:05 mannwhitneyu_NumHAcceptors.csv
-rw-rw-r-- 1 jaime jaime      129 feb  1 16:05 mannwhitneyu_NumHDonors.csv
-rw-rw-r-- 1 jaime jaime      120 feb  1 16:05 mannwhitneyu_pIC50.csv
-rwxr-xr-x 1 jaime jaime 85055499 feb  1 16:01 Miniconda3-py37_4.8.2-Linux-x86_64.sh
-rw-rw-r-- 1 jaime jaime   176576 feb  1 16:01 molecule.smi
drwxr-xr-x 4 jaime jaime     4096 feb  1 16:01 PaDEL-Descriptor
-rw-r--r-- 1 jaime jaime      231 feb  1 16:01 padel.sh
-rw-rw-r-- 1 jaime jaime    13917 feb  1 16:05 plot_bioactivity_class.pdf
-rw-rw-r-- 1 jaime jaime    16842 feb  1 16:05 plot_ic50.pdf
-rw-rw-r-- 1 jaime jaime    14611 feb  1 16:05 plot_LogP.pdf
-rw-rw-r-- 1 jaime jaime    14255 feb  1 16:05 plot_MW.pdf
-rw-rw-r-- 1 jaime jaime   435080 feb  1 16:05 plot_MW_vs_LogP.pdf
-rw-rw-r-- 1 jaime jaime    15331 feb  1 16:05 plot_NumHAcceptors.pdf
-rw-rw-r-- 1 jaime jaime    15492 feb  1 16:05 plot_NumHDonors.pdf
-rw-rw-r-- 1 jaime jaime  1163220 feb  1 16:05 results.zip
-rw-rw-r-- 1 jaime jaime    89239 feb  1 16:03 tessstttyyy.png
-rw-rw-r-- 1 jaime jaime  4607412 feb  1 16:01 trpv1_06_bioactivity_data_3class_pIC50_pubchem_fp.csv
-rw-rw-r-- 1 jaime jaime   381661 feb  1 16:05 trpv1_bioactivity_data_2class_pIC50.csv
-rw-r--r-- 1 jaime jaime   379227 feb  1 16:04 v2_1.ipynb
-rw-r--r-- 1 jaime jaime   283198 feb  1 16:01 v2_2.ipynb
-rw-r--r-- 1 jaime jaime   312451 feb  1 16:01 v2_3.ipynb
-rw-r--r-- 1 jaime jaime    47414 feb  1 16:01 v2_4.ipynb
-rw-r--r-- 1 jaime jaime   252587 feb  1 16:01 v2_5.ipynb
-rw-r--r-- 1 jaime jaime   112058 feb  1 16:01 v2_6.ipynb

In [4]:
df3 = pd.read_csv('trpv1_bioactivity_data_2class_pIC50.csv')

In [5]:
df3

,molecule_chembl_id,canonical_smiles,bioactivity_class,standard_value,MW,LogP,NumHDonors,NumHAcceptors,standard_value_norm,pIC50
0,CHEMBL102010,O=C(NCc1ccc(Cl)cc1)Nc1cccc2cnccc12,active,6.0,311.772,4.2099,2.0,2.0,6.0,8.221849
1,CHEMBL104623,CCC(C)(C)c1ccc(CCC(=O)Nc2cccc3cnccc23)cc1,active,13.0,346.474,5.4937,1.0,2.0,13.0,7.886057
2,CHEMBL103590,O=C(NCCc1ccc(Cl)c(Cl)c1)Nc1cccc2cnccc12,active,10.0,360.244,4.9058,2.0,2.0,10.0,8.000000
3,CHEMBL102486,O=C(NCc1ccc(Cl)c(C(F)(F)F)c1)Nc1cccc2cnccc12,active,6.0,379.769,5.2287,2.0,2.0,6.0,8.221849
4,CHEMBL320906,O=C(Nc1cc(C(F)(F)F)cc(C(F)(F)F)c1)Nc1cccc2cnccc12,active,32.0,399.294,5.9164,2.0,2.0,32.0,7.494850
...,...,...,...,...,...,...,...,...,...,...
2570,CHEMBL4543647,COc1cc2c(cc1OC)[C@H](c1ccccc1)N(C(=O)N1CCc3cc(...,inactive,53000.0,564.682,6.4362,0.0,5.0,53000.0,4.275724
2571,CHEMBL4588287,COc1cc2c(cc1OC)[C@H](c1ccc(Cl)cc1)N(C(=O)N1CCc...,intermediate,49700.0,633.572,7.7430,0.0,5.0,49700.0,4.303644
2572,CHEMBL4576619,COc1cc2c(cc1OC)[C@H](c1ccc(F)cc1)N(C(=O)N1CCc3...,inactive,68500.0,600.662,6.7144,0.0,5.0,68500.0,4.164309
2573,CHEMBL4647981,CCCCCCC(C)(C)c1cc(OC)cc(OCCCCCCCC(=O)NC2CC2)c1,active,800.0,431.661,6.9412,1.0,3.0,800.0,6.096910
2574,CHEMBL4555711,COc1cc(N[C@@H]2CCCC[C@]2(O)C(F)(F)F)ccc1F,active,25.0,307.287,3.4822,2.0,3.0,25.0,7.602060

In [3]:

data = [{'canonical_smiles': 'O=P(O)(O)C(O)(Cn1ccnc1)P(=O)(O)O', 'molecule_chembl_id': 'CHEMBL924'}]
df3_selection = pd.DataFrame(data)
df3_selection.to_csv('molecule.smi', sep='\t', index=False, header=False)

In [4]:
! cat molecule.smi | head -5

O=P(O)(O)C(O)(Cn1ccnc1)P(=O)(O)O	CHEMBL924

In [5]:
! cat molecule.smi | wc -l

1

## **Calculate fingerprint descriptors**

### **Calculate PaDEL descriptors**

In [6]:
! cat padel.sh

java -Xms1G -Xmx1G -Djava.awt.headless=true -jar ./PaDEL-Descriptor/PaDEL-Descriptor.jar -removesalt -standardizenitro -fingerprints -descriptortypes ./PaDEL-Descriptor/PubchemFingerprinter.xml -dir ./ -file descriptors_output.csv

In [7]:
! bash padel.sh

Processing CHEMBL924 in molecule.smi (1/1).
Descriptor calculation completed in 8.788 secs . Average speed: 8,79 s/mol.

In [8]:
! ls -l

total 95368
-rw-r--r-- 1 jaime jaime  3916980 feb  8 14:33 bioactivity_data.csv
-rw-r--r-- 1 jaime jaime   212391 feb  8 14:33 bioactivity_preprocessed_data.csv
-rw-r--r-- 1 jaime jaime    13122 jun  3 17:13 descriptors_output.csv
-rw-r--r-- 1 jaime jaime     1257 feb  8 14:33 histograma.png
-rw-r--r-- 1 jaime jaime    57463 feb  8 14:33 ids_3+.csv
-rw-r--r-- 1 jaime jaime    27816 feb  8 14:33 ids_todos.csv
drwxr-xr-x 6 jaime jaime     4096 feb  8 14:33 jupyterenv
-rw-r--r-- 1 jaime jaime      122 feb  8 14:33 mannwhitneyu_LogP.csv
-rw-r--r-- 1 jaime jaime      122 feb  8 14:33 mannwhitneyu_MW.csv
-rw-r--r-- 1 jaime jaime      132 feb  8 14:33 mannwhitneyu_NumHAcceptors.csv
-rw-r--r-- 1 jaime jaime      129 feb  8 14:33 mannwhitneyu_NumHDonors.csv
-rw-r--r-- 1 jaime jaime      120 feb  8 14:33 mannwhitneyu_pIC50.csv
-rwxr--r-- 1 jaime jaime 85055499 feb  8 14:33 Miniconda3-py37_4.8.2-Linux-x86_64.sh
-rw-r--r-- 1 jaime jaime       43 jun  3 17:11 molecule.smi
drwxr-xr-x 4 jaime jaime     4096 feb  8 14:33 PaDEL-Descriptor
-rw-r--r-- 1 jaime jaime      231 feb  8 14:33 padel.sh
-rw-r--r-- 1 jaime jaime    13159 may 25 22:37 plot_3_class_oversampling.pdf
-rw-r--r-- 1 jaime jaime    13136 may 25 22:37 plot_3_class.pdf
-rw-r--r-- 1 jaime jaime    13917 feb  8 14:33 plot_bioactivity_class.pdf
-rw-r--r-- 1 jaime jaime    16842 feb  8 14:33 plot_ic50.pdf
-rw-r--r-- 1 jaime jaime    14611 feb  8 14:33 plot_LogP.pdf
-rw-r--r-- 1 jaime jaime    14255 feb  8 14:33 plot_MW.pdf
-rw-r--r-- 1 jaime jaime   435080 feb  8 14:33 plot_MW_vs_LogP.pdf
-rw-r--r-- 1 jaime jaime    15331 feb  8 14:33 plot_NumHAcceptors.pdf
-rw-r--r-- 1 jaime jaime    15492 feb  8 14:33 plot_NumHDonors.pdf
-rw-r--r-- 1 jaime jaime  1163220 feb  8 14:33 results.zip
-rw-r--r-- 1 jaime jaime    89239 feb  8 14:33 tessstttyyy.png
-rw-r--r-- 1 jaime jaime  4607412 feb  8 14:33 trpv1_06_bioactivity_data_3class_pIC50_pubchem_fp.csv
-rw-r--r-- 1 jaime jaime   381661 feb  8 14:33 trpv1_bioactivity_data_2class_pIC50.csv
-rw-r--r-- 1 jaime jaime   379227 mar 16 12:28 v2_1.ipynb
-rw-r--r-- 1 jaime jaime   281972 feb  8 16:14 v2_2.ipynb
-rw-r--r-- 1 jaime jaime   312171 jun  3 17:11 v2_3.ipynb
-rw-r--r-- 1 jaime jaime    47134 mar 15 23:50 v2_4.ipynb
-rw-r--r-- 1 jaime jaime   252975 mar 16 12:33 v2_5.ipynb
-rw-r--r-- 1 jaime jaime   213465 may 25 22:42 v2_6.ipynb

## **Preparing the X and Y Data Matrices**

### **X data matrix**

In [9]:
df3_X = pd.read_csv('descriptors_output.csv')

In [10]:
df3_X

,Name,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,CHEMBL924,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [12]:
df3_X = df3_X.drop(columns=['Name'])
df3_X

KeyError: "['Name'] not found in axis"

## **Y variable**

### **Convert IC50 to pIC50**

In [15]:
df3_Y = pd.DataFrame([{'pIC50':0}])
df3_Y

   pIC50
0      0

## **Combining X and Y variable**

In [17]:
dataset3 = pd.concat([df3_X,df3_Y], axis=1)
dataset3 = pd.concat([dataset3, pd.DataFrame([{'standard_value':0}])], axis=1)

In [18]:
dataset3

,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,PubchemFP9,...,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880,pIC50,standard_value
0,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [19]:
dataset3.to_csv('trpv1_06_bioactivity_data_3class_pIC50_pubchem_fp_1.csv', index=False)

# **Let's download the CSV file to your local computer for the Part 3B (Model Building).**